[workspace]
resolver = "2"
members = ["apps/api", "crates/shared"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
shared = { path = "crates/shared" }

axum = "0.8"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6", features = ["trace", "cors"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "migrate", "chrono", "time", "postgres", "uuid"] }
ts-rs = "12"
log = "0.4.29"
dotenv = "0.15.0"
async-trait = "0.1.89"
uuid = { version = "1.19.0", features = ["v4", "serde"] }
jsonwebtoken = { version = "10.2.0", features = ["rust_crypto"] }
time = "0.3.45"
thiserror = "2.0.18"
chrono = { version = "0.4.43", features = ["serde"] }
bcrypt = "0.18.0"
sha2 = "0.10"